from ctypes import *

VkFramebufferCreateFlags = c_uint32  # bits: VkFramebufferCreateFlagBits
VkQueryPoolCreateFlags = c_uint32  # bits: VkQueryPoolCreateFlagBits
VkRenderPassCreateFlags = c_uint32  # bits: VkRenderPassCreateFlagBits
VkSamplerCreateFlags = c_uint32  # bits: VkSamplerCreateFlagBits
VkPipelineLayoutCreateFlags = c_uint32  # bits: VkPipelineLayoutCreateFlagBits
VkPipelineCacheCreateFlags = c_uint32  # bits: VkPipelineCacheCreateFlagBits
VkPipelineDepthStencilStateCreateFlags = c_uint32
VkPipelineDynamicStateCreateFlags = c_uint32
VkPipelineColorBlendStateCreateFlags = c_uint32
VkPipelineMultisampleStateCreateFlags = c_uint32
VkPipelineRasterizationStateCreateFlags = c_uint32
VkPipelineViewportStateCreateFlags = c_uint32
VkPipelineTessellationStateCreateFlags = c_uint32
VkPipelineInputAssemblyStateCreateFlags = c_uint32
VkPipelineVertexInputStateCreateFlags = c_uint32
VkPipelineShaderStageCreateFlags = c_uint32  # bits: VkPipelineShaderStageCreateFlagBits
VkDescriptorSetLayoutCreateFlags = c_uint32  # bits: VkDescriptorSetLayoutCreateFlagBits
VkBufferViewCreateFlags = c_uint32
VkInstanceCreateFlags = c_uint32  # bits: VkInstanceCreateFlagBits
VkDeviceCreateFlags = c_uint32
VkDeviceQueueCreateFlags = c_uint32  # bits: VkDeviceQueueCreateFlagBits
VkQueueFlags = c_uint32  # bits: VkQueueFlagBits
VkMemoryPropertyFlags = c_uint32  # bits: VkMemoryPropertyFlagBits
VkMemoryHeapFlags = c_uint32  # bits: VkMemoryHeapFlagBits
VkAccessFlags = c_uint32  # bits: VkAccessFlagBits
VkBufferUsageFlags = c_uint32  # bits: VkBufferUsageFlagBits
VkBufferCreateFlags = c_uint32  # bits: VkBufferCreateFlagBits
VkShaderStageFlags = c_uint32  # bits: VkShaderStageFlagBits
VkImageUsageFlags = c_uint32  # bits: VkImageUsageFlagBits
VkImageCreateFlags = c_uint32  # bits: VkImageCreateFlagBits
VkImageViewCreateFlags = c_uint32  # bits: VkImageViewCreateFlagBits
VkPipelineCreateFlags = c_uint32  # bits: VkPipelineCreateFlagBits
VkColorComponentFlags = c_uint32  # bits: VkColorComponentFlagBits
VkFenceCreateFlags = c_uint32  # bits: VkFenceCreateFlagBits
VkSemaphoreCreateFlags = c_uint32
VkFormatFeatureFlags = c_uint32  # bits: VkFormatFeatureFlagBits
VkQueryControlFlags = c_uint32  # bits: VkQueryControlFlagBits
VkQueryResultFlags = c_uint32  # bits: VkQueryResultFlagBits
VkShaderModuleCreateFlags = c_uint32
VkEventCreateFlags = c_uint32  # bits: VkEventCreateFlagBits
VkCommandPoolCreateFlags = c_uint32  # bits: VkCommandPoolCreateFlagBits
VkCommandPoolResetFlags = c_uint32  # bits: VkCommandPoolResetFlagBits
VkCommandBufferResetFlags = c_uint32  # bits: VkCommandBufferResetFlagBits
VkCommandBufferUsageFlags = c_uint32  # bits: VkCommandBufferUsageFlagBits
VkQueryPipelineStatisticFlags = c_uint32  # bits: VkQueryPipelineStatisticFlagBits
VkMemoryMapFlags = c_uint32  # bits: VkMemoryMapFlagBits
VkMemoryUnmapFlags = c_uint32  # bits: VkMemoryUnmapFlagBits
VkImageAspectFlags = c_uint32  # bits: VkImageAspectFlagBits
VkSparseMemoryBindFlags = c_uint32  # bits: VkSparseMemoryBindFlagBits
VkSparseImageFormatFlags = c_uint32  # bits: VkSparseImageFormatFlagBits
VkSubpassDescriptionFlags = c_uint32  # bits: VkSubpassDescriptionFlagBits
VkPipelineStageFlags = c_uint32  # bits: VkPipelineStageFlagBits
VkSampleCountFlags = c_uint32  # bits: VkSampleCountFlagBits
VkAttachmentDescriptionFlags = c_uint32  # bits: VkAttachmentDescriptionFlagBits
VkStencilFaceFlags = c_uint32  # bits: VkStencilFaceFlagBits
VkCullModeFlags = c_uint32  # bits: VkCullModeFlagBits
VkDescriptorPoolCreateFlags = c_uint32  # bits: VkDescriptorPoolCreateFlagBits
VkDescriptorPoolResetFlags = c_uint32
VkDependencyFlags = c_uint32  # bits: VkDependencyFlagBits
VkSubgroupFeatureFlags = c_uint32  # bits: VkSubgroupFeatureFlagBits
VkIndirectCommandsLayoutUsageFlagsNV = c_uint32  # bits: VkIndirectCommandsLayoutUsageFlagBitsNV
VkIndirectStateFlagsNV = c_uint32  # bits: VkIndirectStateFlagBitsNV
VkGeometryFlagsKHR = c_uint32  # bits: VkGeometryFlagBitsKHR
VkGeometryInstanceFlagsKHR = c_uint32  # bits: VkGeometryInstanceFlagBitsKHR
VkClusterAccelerationStructureGeometryFlagsNV = c_uint32  # bits: VkClusterAccelerationStructureGeometryFlagBitsNV
VkClusterAccelerationStructureClusterFlagsNV = c_uint32  # bits: VkClusterAccelerationStructureClusterFlagBitsNV
VkClusterAccelerationStructureAddressResolutionFlagsNV = c_uint32  # bits: VkClusterAccelerationStructureAddressResolutionFlagBitsNV
VkBuildAccelerationStructureFlagsKHR = c_uint32  # bits: VkBuildAccelerationStructureFlagBitsKHR
VkPrivateDataSlotCreateFlags = c_uint32
VkAccelerationStructureCreateFlagsKHR = c_uint32  # bits: VkAccelerationStructureCreateFlagBitsKHR
VkDescriptorUpdateTemplateCreateFlags = c_uint32
VkPipelineCreationFeedbackFlags = c_uint32  # bits: VkPipelineCreationFeedbackFlagBits
VkPerformanceCounterDescriptionFlagsKHR = c_uint32  # bits: VkPerformanceCounterDescriptionFlagBitsKHR
VkAcquireProfilingLockFlagsKHR = c_uint32  # bits: VkAcquireProfilingLockFlagBitsKHR
VkSemaphoreWaitFlags = c_uint32  # bits: VkSemaphoreWaitFlagBits
VkPipelineCompilerControlFlagsAMD = c_uint32  # bits: VkPipelineCompilerControlFlagBitsAMD
VkShaderCorePropertiesFlagsAMD = c_uint32  # bits: VkShaderCorePropertiesFlagBitsAMD
VkDeviceDiagnosticsConfigFlagsNV = c_uint32  # bits: VkDeviceDiagnosticsConfigFlagBitsNV
VkRefreshObjectFlagsKHR = c_uint32  # bits: VkRefreshObjectFlagBitsKHR
VkAccessFlags2 = c_uint64  # bits: VkAccessFlagBits2
VkPipelineStageFlags2 = c_uint64  # bits: VkPipelineStageFlagBits2
VkAccelerationStructureMotionInfoFlagsNV = c_uint32
VkAccelerationStructureMotionInstanceFlagsNV = c_uint32
VkFormatFeatureFlags2 = c_uint64  # bits: VkFormatFeatureFlagBits2
VkRenderingFlags = c_uint32  # bits: VkRenderingFlagBits
VkMemoryDecompressionMethodFlagsEXT = c_uint64  # bits: VkMemoryDecompressionMethodFlagBitsEXT
VkDeviceFaultFlagsKHR = c_uint32  # bits: VkDeviceFaultFlagBitsKHR
VkBuildMicromapFlagsEXT = c_uint32  # bits: VkBuildMicromapFlagBitsEXT
VkMicromapCreateFlagsEXT = c_uint32  # bits: VkMicromapCreateFlagBitsEXT
VkIndirectCommandsLayoutUsageFlagsEXT = c_uint32  # bits: VkIndirectCommandsLayoutUsageFlagBitsEXT
VkIndirectCommandsInputModeFlagsEXT = c_uint32  # bits: VkIndirectCommandsInputModeFlagBitsEXT
VkDirectDriverLoadingFlagsLUNARG = c_uint32
VkPipelineCreateFlags2 = c_uint64  # bits: VkPipelineCreateFlagBits2
VkBufferUsageFlags2 = c_uint64  # bits: VkBufferUsageFlagBits2
VkAddressCopyFlagsKHR = c_uint32  # bits: VkAddressCopyFlagBitsKHR
VkTensorCreateFlagsARM = c_uint64  # bits: VkTensorCreateFlagBitsARM
VkTensorUsageFlagsARM = c_uint64  # bits: VkTensorUsageFlagBitsARM
VkTensorViewCreateFlagsARM = c_uint64  # bits: VkTensorViewCreateFlagBitsARM
VkDataGraphPipelineSessionCreateFlagsARM = c_uint64  # bits: VkDataGraphPipelineSessionCreateFlagBitsARM
VkDataGraphPipelineDispatchFlagsARM = c_uint64  # bits: VkDataGraphPipelineDispatchFlagBitsARM
VkVideoEncodeRgbModelConversionFlagsVALVE = c_uint32  # bits: VkVideoEncodeRgbModelConversionFlagBitsVALVE
VkVideoEncodeRgbRangeCompressionFlagsVALVE = c_uint32  # bits: VkVideoEncodeRgbRangeCompressionFlagBitsVALVE
VkVideoEncodeRgbChromaOffsetFlagsVALVE = c_uint32  # bits: VkVideoEncodeRgbChromaOffsetFlagBitsVALVE
VkSpirvResourceTypeFlagsEXT = c_uint32  # bits: VkSpirvResourceTypeFlagBitsEXT
VkAddressCommandFlagsKHR = c_uint32  # bits: VkAddressCommandFlagBitsKHR
VkCompositeAlphaFlagsKHR = c_uint32  # bits: VkCompositeAlphaFlagBitsKHR
VkDisplayPlaneAlphaFlagsKHR = c_uint32  # bits: VkDisplayPlaneAlphaFlagBitsKHR
VkSurfaceTransformFlagsKHR = c_uint32  # bits: VkSurfaceTransformFlagBitsKHR
VkSwapchainCreateFlagsKHR = c_uint32  # bits: VkSwapchainCreateFlagBitsKHR
VkDisplayModeCreateFlagsKHR = c_uint32
VkDisplaySurfaceCreateFlagsKHR = c_uint32
VkAndroidSurfaceCreateFlagsKHR = c_uint32
VkViSurfaceCreateFlagsNN = c_uint32
VkWaylandSurfaceCreateFlagsKHR = c_uint32
VkUbmSurfaceCreateFlagsSEC = c_uint32
VkWin32SurfaceCreateFlagsKHR = c_uint32
VkXlibSurfaceCreateFlagsKHR = c_uint32
VkXcbSurfaceCreateFlagsKHR = c_uint32
VkDirectFBSurfaceCreateFlagsEXT = c_uint32
VkIOSSurfaceCreateFlagsMVK = c_uint32
VkMacOSSurfaceCreateFlagsMVK = c_uint32
VkMetalSurfaceCreateFlagsEXT = c_uint32
VkImagePipeSurfaceCreateFlagsFUCHSIA = c_uint32
VkStreamDescriptorSurfaceCreateFlagsGGP = c_uint32
VkHeadlessSurfaceCreateFlagsEXT = c_uint32
VkScreenSurfaceCreateFlagsQNX = c_uint32
VkPeerMemoryFeatureFlags = c_uint32  # bits: VkPeerMemoryFeatureFlagBits
VkMemoryAllocateFlags = c_uint32  # bits: VkMemoryAllocateFlagBits
VkDeviceGroupPresentModeFlagsKHR = c_uint32  # bits: VkDeviceGroupPresentModeFlagBitsKHR
VkDebugReportFlagsEXT = c_uint32  # bits: VkDebugReportFlagBitsEXT
VkCommandPoolTrimFlags = c_uint32
VkExternalMemoryHandleTypeFlagsNV = c_uint32  # bits: VkExternalMemoryHandleTypeFlagBitsNV
VkClusterAccelerationStructureIndexFormatFlagsNV = c_uint32  # bits: VkClusterAccelerationStructureIndexFormatFlagBitsNV
VkExternalMemoryFeatureFlagsNV = c_uint32  # bits: VkExternalMemoryFeatureFlagBitsNV
VkExternalMemoryHandleTypeFlags = c_uint32  # bits: VkExternalMemoryHandleTypeFlagBits
VkExternalMemoryFeatureFlags = c_uint32  # bits: VkExternalMemoryFeatureFlagBits
VkExternalSemaphoreHandleTypeFlags = c_uint32  # bits: VkExternalSemaphoreHandleTypeFlagBits
VkExternalSemaphoreFeatureFlags = c_uint32  # bits: VkExternalSemaphoreFeatureFlagBits
VkSemaphoreImportFlags = c_uint32  # bits: VkSemaphoreImportFlagBits
VkExternalFenceHandleTypeFlags = c_uint32  # bits: VkExternalFenceHandleTypeFlagBits
VkExternalFenceFeatureFlags = c_uint32  # bits: VkExternalFenceFeatureFlagBits
VkFenceImportFlags = c_uint32  # bits: VkFenceImportFlagBits
VkSurfaceCounterFlagsEXT = c_uint32  # bits: VkSurfaceCounterFlagBitsEXT
VkPipelineViewportSwizzleStateCreateFlagsNV = c_uint32
VkPipelineDiscardRectangleStateCreateFlagsEXT = c_uint32
VkPipelineCoverageToColorStateCreateFlagsNV = c_uint32
VkPipelineCoverageModulationStateCreateFlagsNV = c_uint32
VkPipelineCoverageReductionStateCreateFlagsNV = c_uint32
VkValidationCacheCreateFlagsEXT = c_uint32
VkDebugUtilsMessageSeverityFlagsEXT = c_uint32  # bits: VkDebugUtilsMessageSeverityFlagBitsEXT
VkDebugUtilsMessageTypeFlagsEXT = c_uint32  # bits: VkDebugUtilsMessageTypeFlagBitsEXT
VkDebugUtilsMessengerCreateFlagsEXT = c_uint32
VkDebugUtilsMessengerCallbackDataFlagsEXT = c_uint32
VkDeviceMemoryReportFlagsEXT = c_uint32
VkPipelineRasterizationConservativeStateCreateFlagsEXT = c_uint32
VkDescriptorBindingFlags = c_uint32  # bits: VkDescriptorBindingFlagBits
VkConditionalRenderingFlagsEXT = c_uint32  # bits: VkConditionalRenderingFlagBitsEXT
VkResolveModeFlags = c_uint32  # bits: VkResolveModeFlagBits
VkPipelineRasterizationStateStreamCreateFlagsEXT = c_uint32
VkPipelineRasterizationDepthClipStateCreateFlagsEXT = c_uint32
VkSwapchainImageUsageFlagsANDROID = c_uint32  # bits: VkSwapchainImageUsageFlagBitsANDROID
VkToolPurposeFlags = c_uint32  # bits: VkToolPurposeFlagBits
VkSubmitFlags = c_uint32  # bits: VkSubmitFlagBits
VkImageFormatConstraintsFlagsFUCHSIA = c_uint32
VkHostImageCopyFlags = c_uint32  # bits: VkHostImageCopyFlagBits
VkPartitionedAccelerationStructureInstanceFlagsNV = c_uint32  # bits: VkPartitionedAccelerationStructureInstanceFlagBitsNV
VkImageConstraintsInfoFlagsFUCHSIA = c_uint32  # bits: VkImageConstraintsInfoFlagBitsFUCHSIA
VkGraphicsPipelineLibraryFlagsEXT = c_uint32  # bits: VkGraphicsPipelineLibraryFlagBitsEXT
VkImageCompressionFlagsEXT = c_uint32  # bits: VkImageCompressionFlagBitsEXT
VkImageCompressionFixedRateFlagsEXT = c_uint32  # bits: VkImageCompressionFixedRateFlagBitsEXT
VkExportMetalObjectTypeFlagsEXT = c_uint32  # bits: VkExportMetalObjectTypeFlagBitsEXT
VkRenderingAttachmentFlagsKHR = c_uint32  # bits: VkRenderingAttachmentFlagBitsKHR
VkResolveImageFlagsKHR = c_uint32  # bits: VkResolveImageFlagBitsKHR
VkDeviceAddressBindingFlagsEXT = c_uint32  # bits: VkDeviceAddressBindingFlagBitsEXT
VkOpticalFlowGridSizeFlagsNV = c_uint32  # bits: VkOpticalFlowGridSizeFlagBitsNV
VkOpticalFlowUsageFlagsNV = c_uint32  # bits: VkOpticalFlowUsageFlagBitsNV
VkOpticalFlowSessionCreateFlagsNV = c_uint32  # bits: VkOpticalFlowSessionCreateFlagBitsNV
VkOpticalFlowExecuteFlagsNV = c_uint32  # bits: VkOpticalFlowExecuteFlagBitsNV
VkFrameBoundaryFlagsEXT = c_uint32  # bits: VkFrameBoundaryFlagBitsEXT
VkPresentScalingFlagsKHR = c_uint32  # bits: VkPresentScalingFlagBitsKHR
VkPresentGravityFlagsKHR = c_uint32  # bits: VkPresentGravityFlagBitsKHR
VkShaderCreateFlagsEXT = c_uint32  # bits: VkShaderCreateFlagBitsEXT
VkTileShadingRenderPassFlagsQCOM = c_uint32  # bits: VkTileShadingRenderPassFlagBitsQCOM
VkPhysicalDeviceSchedulingControlsFlagsARM = c_uint64  # bits: VkPhysicalDeviceSchedulingControlsFlagBitsARM
VkSurfaceCreateFlagsOHOS = c_uint32
VkPresentStageFlagsEXT = c_uint32  # bits: VkPresentStageFlagBitsEXT
VkPastPresentationTimingFlagsEXT = c_uint32  # bits: VkPastPresentationTimingFlagBitsEXT
VkPresentTimingInfoFlagsEXT = c_uint32  # bits: VkPresentTimingInfoFlagBitsEXT
VkSwapchainImageUsageFlagsOHOS = c_uint32  # bits: VkSwapchainImageUsageFlagBitsOHOS
VkPerformanceCounterDescriptionFlagsARM = c_uint32
VkShaderInstrumentationValuesFlagsARM = c_uint32
VkDataGraphTOSAQualityFlagsARM = c_uint32  # bits: VkDataGraphTOSAQualityFlagBitsARM
VkDataGraphOpticalFlowGridSizeFlagsARM = c_uint32  # bits: VkDataGraphOpticalFlowGridSizeFlagBitsARM
VkDataGraphOpticalFlowImageUsageFlagsARM = c_uint32  # bits: VkDataGraphOpticalFlowImageUsageFlagBitsARM
VkDataGraphOpticalFlowCreateFlagsARM = c_uint32  # bits: VkDataGraphOpticalFlowCreateFlagBitsARM
VkDataGraphOpticalFlowExecuteFlagsARM = c_uint32  # bits: VkDataGraphOpticalFlowExecuteFlagBitsARM
VkVideoCodecOperationFlagsKHR = c_uint32  # bits: VkVideoCodecOperationFlagBitsKHR
VkVideoCapabilityFlagsKHR = c_uint32  # bits: VkVideoCapabilityFlagBitsKHR
VkVideoSessionCreateFlagsKHR = c_uint32  # bits: VkVideoSessionCreateFlagBitsKHR
VkVideoSessionParametersCreateFlagsKHR = c_uint32  # bits: VkVideoSessionParametersCreateFlagBitsKHR
VkVideoBeginCodingFlagsKHR = c_uint32
VkVideoEndCodingFlagsKHR = c_uint32
VkVideoCodingControlFlagsKHR = c_uint32  # bits: VkVideoCodingControlFlagBitsKHR
VkVideoDecodeUsageFlagsKHR = c_uint32  # bits: VkVideoDecodeUsageFlagBitsKHR
VkVideoDecodeCapabilityFlagsKHR = c_uint32  # bits: VkVideoDecodeCapabilityFlagBitsKHR
VkVideoDecodeFlagsKHR = c_uint32
VkVideoDecodeH264PictureLayoutFlagsKHR = c_uint32  # bits: VkVideoDecodeH264PictureLayoutFlagBitsKHR
VkVideoEncodeFlagsKHR = c_uint32  # bits: VkVideoEncodeFlagBitsKHR
VkVideoEncodeUsageFlagsKHR = c_uint32  # bits: VkVideoEncodeUsageFlagBitsKHR
VkVideoEncodeContentFlagsKHR = c_uint32  # bits: VkVideoEncodeContentFlagBitsKHR
VkVideoEncodeCapabilityFlagsKHR = c_uint32  # bits: VkVideoEncodeCapabilityFlagBitsKHR
VkVideoEncodeFeedbackFlagsKHR = c_uint32  # bits: VkVideoEncodeFeedbackFlagBitsKHR
VkVideoEncodeRateControlFlagsKHR = c_uint32
VkVideoEncodeRateControlModeFlagsKHR = c_uint32  # bits: VkVideoEncodeRateControlModeFlagBitsKHR
VkVideoEncodeIntraRefreshModeFlagsKHR = c_uint32  # bits: VkVideoEncodeIntraRefreshModeFlagBitsKHR
VkVideoChromaSubsamplingFlagsKHR = c_uint32  # bits: VkVideoChromaSubsamplingFlagBitsKHR
VkVideoComponentBitDepthFlagsKHR = c_uint32  # bits: VkVideoComponentBitDepthFlagBitsKHR
VkVideoEncodeH264CapabilityFlagsKHR = c_uint32  # bits: VkVideoEncodeH264CapabilityFlagBitsKHR
VkVideoEncodeH264StdFlagsKHR = c_uint32  # bits: VkVideoEncodeH264StdFlagBitsKHR
VkVideoEncodeH264RateControlFlagsKHR = c_uint32  # bits: VkVideoEncodeH264RateControlFlagBitsKHR
VkVideoEncodeH265CapabilityFlagsKHR = c_uint32  # bits: VkVideoEncodeH265CapabilityFlagBitsKHR
VkVideoEncodeH265StdFlagsKHR = c_uint32  # bits: VkVideoEncodeH265StdFlagBitsKHR
VkVideoEncodeH265RateControlFlagsKHR = c_uint32  # bits: VkVideoEncodeH265RateControlFlagBitsKHR
VkVideoEncodeH265CtbSizeFlagsKHR = c_uint32  # bits: VkVideoEncodeH265CtbSizeFlagBitsKHR
VkVideoEncodeH265TransformBlockSizeFlagsKHR = c_uint32  # bits: VkVideoEncodeH265TransformBlockSizeFlagBitsKHR
VkVideoEncodeAV1CapabilityFlagsKHR = c_uint32  # bits: VkVideoEncodeAV1CapabilityFlagBitsKHR
VkVideoEncodeAV1StdFlagsKHR = c_uint32  # bits: VkVideoEncodeAV1StdFlagBitsKHR
VkVideoEncodeAV1RateControlFlagsKHR = c_uint32  # bits: VkVideoEncodeAV1RateControlFlagBitsKHR
VkVideoEncodeAV1SuperblockSizeFlagsKHR = c_uint32  # bits: VkVideoEncodeAV1SuperblockSizeFlagBitsKHR
VkAccessFlags3KHR = c_uint64  # bits: VkAccessFlagBits3KHR